{
  "tests/integration/cloudformation/api/test_extensions_hooks.py::TestExtensionsHooks::test_hook_deployment": {
    "recorded-date": "03-03-2023, 13:33:46",
    "recorded-content": {
      "event_error": {
        "EventId": "myb3B4550BC-7cb57c6f-f895-48b7-ac13-2fa3366301e0",
        "HookFailureMode": "FAIL",
        "HookInvocationPoint": "PRE_PROVISION",
        "HookStatus": "HOOK_COMPLETE_FAILED",
        "HookStatusReason": "Hook failed with message: Intentional fail",
        "HookType": "LocalStack::Testing::DeployableHook",
        "LogicalResourceId": "myb3B4550BC",
        "PhysicalResourceId": "",
        "ResourceStatus": "CREATE_IN_PROGRESS",
        "ResourceType": "AWS::S3::Bucket",
        "StackId": "arn:aws:cloudformation:<region>:111111111111:stack/<stack-name:1>/<resource:1>",
        "StackName": "<stack-name:1>",
        "Timestamp": "timestamp"
      }
    }
  }
}
